server:
  port: 8885


spring:
  application:
    name: service-nlp

eureka:
  client:
    serviceUrl:
      defaultZone: http://biggsai.com:8881/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    hostname: ${eureka.instance.ip-address}
    ip-address: 47.100.58.250
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}


