server:
  port: 8888

spring:
  application:
    name: service-zuul


eureka:
  client:
    serviceUrl:
      defaultZone: http://biggsai.com:8881/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    hostname: ${eureka.instance.ip-address}
    ip-address: 47.100.58.250
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
zuul:
  routes:
    api-a:
      path: /image/**
      serviceId: service-image
    api-b:
       path: /**
       serviceId: service-nlp



